Layout/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 1500
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false